---
title: "Using a Monte Carlo method to predict Fantasy Football Scores"
author: "Tom Constant"
date: "16 May 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs}
library(tidyverse)
library(knitr)
```

## The Model

```{r model}

monte_carlo <- function(player_file, N = 500, start_week = "current"){
  
  data <- read_csv(player_file, col_types = cols())
  
  if(start_week == "current") start_week <- length(data$points[data$id==data$id[1]])+1
  
  model <- list()
  
  for(player in unique(data$id)){
    
    data_loop <- data[data$id == player,]
    
    total_points <- numeric(N)
    
    points <- data_loop$points - data_loop$event_transfers_cost.1
    points <- points[(1:(start_week-1))]
    
    for(j in 1:N){ # season iteration loop
      
      for(i in (start_week:39)){ # remaining gameweek loop
        
        pdf <- density(points)
        
        points[i] <- approx(
          cumsum(pdf$y)/sum(pdf$y),
          pdf$x,
          runif(1),
          yleft = min(data$points - data$event_transfers_cost.1),
          yright = max(data$points - data$event_transfers_cost.1),
          rule = 2
        )$y
        
        if(points[i]< min(data$points - data$event_transfers_cost.1)) points[i] <- min(data$points - data$event_transfers_cost.1)
        if(points[i]>max(data$points - data$event_transfers_cost.1)) points[i] <- max(data$points - data$event_transfers_cost.1)
        
      }
      
      points <- points[1:38]
      
      total_points[j] <- sum(points)
      
    }
    
    model[[paste(data_loop$player_first_name, data_loop$player_last_name)[1]]] <- total_points
    
  }
  
  model <-
    model %>% 
    bind_rows() %>%
    mutate(season_number = row_number()) %>%
    gather(key = player, value = final_score, seq_along(unique(data$id)))
  

rank_predictions <- 
  model %>% 
  group_by(season_number) %>% 
  mutate(rank = rank(-final_score)) %>%
  group_by(player, rank) %>%
  tally() %>% 
  ungroup() %>% 
  complete(player, rank, fill = list(n = 0)) %>%
  mutate(pct = 100*n/N)
  
  place <- list()
  
  for(i in 1:length(unique(data$id))){
    place[[i]] <- 
      rank_predictions %>%
      filter(rank == i) %>%
      arrange(-pct) %>%
      #mutate(pct = pct %>% round(1) %>% paste0("%")) %>%
      select(manager = player, `number of seasons won` = n, `percentage of seasons won` = pct)
  }
  
  return(list(model = model, 
              rank_predictions = rank_predictions, 
              place = place))
}

```


```{r week_by_week}

week_by_week_1st_place <- function(player_file){
  
  set.seed(123)
  
  results <- list()
  
  for (i in 3:38){
    results[[i]] <- monte_carlo(player_file, N = 500, start_week = i)
  }
  
  p1 <- 
  lapply(lapply(results, function(x) x[[3]]), function(x) x[[1]]) %>%
    bind_rows(.id = "gameweek") %>%
    mutate(gameweek = (gameweek %>% as.integer()) + 2) %>%
    ggplot(aes(x = gameweek, 
               y = `percentage of seasons won`, 
               group = manager, 
               colour = manager)) + 
    geom_line() + 
    geom_point() +
    #geom_area(aes(fill = manager), position = "fill", col = 1)+
    theme_bw()
  
  print(p1)
  
  p2 <-
  lapply(results, function(x) x[[1]]) %>%
    bind_rows(.id = "gameweek") %>%
    mutate(gameweek = (gameweek %>% as.integer()) + 2) %>%
    ggplot(aes(x = gameweek, y = final_score, fill= player)) + 
    stat_summary(geom = "ribbon", alpha = 0.025, fun.y = mean, fun.ymax = max, fun.ymin = min) + 
    theme_bw() + 
    geom_jitter(aes(colour = player), alpha = 0.025/5) +
    stat_summary(aes(colour = player), geom="line", lwd = 1.25) +
    ylab("final predicted score")
  
  print(p2)
  
  invisible(results)
}

```

```{r physics}
result_phys <- week_by_week_1st_place("../data/history_Physics-Fantasy-Football.csv") 
```

```{r}

fs <- data.frame(player = c("Tom Constant", "Ben Tremain", "Ian Hooper", "Tom Graham", "Gareth Ward"), actual_final_score = c(2165, 2302, 2154, 2167, 2014))
  
p2 <-
  lapply(result_phys, function(x) x[[1]]) %>%
    bind_rows(.id = "gameweek") %>%
    mutate(gameweek = (gameweek %>% as.integer()) + 2) %>%
    full_join(fs)

p2 %>%
  group_by(player, gameweek) %>%
  mutate(diff = final_score-actual_final_score) %>%
  summarise(avg = mean(diff)) %>%
  ggplot(aes(gameweek, avg, colour = player)) + 
  geom_line() + 
  geom_point() + 
  theme_bw() + ylab("prediction error (absolute)")

```

```{r uoe}
result_uoe <- week_by_week_1st_place("../data/history_UoE-Premiership.csv") 
```

```{r}
```{r}

fs <- data.frame(player = c("Corinne Greaves", "Ben Tremain", "John Greaves", "Tom Constant", "Jon Vague", "James Westwood", "Nicholas Taylor", "Tim Leveridge", "Richard King"), actual_final_score = c(2323,2302,2193,2165,2134,2047,1928,1868,1649))
  
p2 <-
  lapply(result_uoe, function(x) x[[1]]) %>%
    bind_rows(.id = "gameweek") %>%
    mutate(gameweek = (gameweek %>% as.integer()) + 2) %>%
    full_join(fs)

p2 %>%
  group_by(player, gameweek) %>%
  mutate(diff = final_score-actual_final_score) %>%
  summarise(avg = mean(diff)) %>%
  ggplot(aes(gameweek, avg, colour = player)) + 
  geom_line() + 
  geom_point() + 
  theme_bw() + ylab("prediction error (absolute)")

```

```



